-- Fechamento de folha (trava de período) + Auditoria
-- 1) fechamentos: períodos de folha já pagos ficam travados contra alteração
-- 2) auditoria: log automático de toda alteração nas tabelas principais

-- ── Fechamentos ───────────────────────────────────────────────────────────────
create table if not exists fechamentos (
  id bigint generated by default as identity primary key,
  data_inicio date not null,
  data_fim date not null,
  status text not null default 'fechado' check (status in ('fechado', 'reaberto')),
  fechado_por text,
  reaberto_por text,
  obs text,
  created_at timestamptz not null default now()
);

alter table fechamentos enable row level security;
create policy "fechamentos_select" on fechamentos for select using (true);
create policy "fechamentos_insert" on fechamentos for insert with check (true);
create policy "fechamentos_update" on fechamentos for update using (true);
-- sem policy de delete: fechamentos nunca são apagados, só reabertos

-- Trava: bloqueia insert/update/delete em datas dentro de período fechado
create or replace function bloquear_periodo_fechado() returns trigger
language plpgsql as $$
declare
  lim date;
begin
  select max(data_fim) into lim from fechamentos where status = 'fechado';
  if lim is not null then
    if (tg_op in ('INSERT', 'UPDATE') and new.data <= lim)
       or (tg_op in ('UPDATE', 'DELETE') and old.data <= lim) then
      raise exception 'Período fechado até %. Reabra o fechamento em Fechamento & Auditoria para alterar.', to_char(lim, 'DD/MM/YYYY');
    end if;
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end $$;

drop trigger if exists trava_registros on registros_producao;
create trigger trava_registros before insert or update or delete on registros_producao
  for each row execute function bloquear_periodo_fechado();

drop trigger if exists trava_cq on controle_qualidade;
create trigger trava_cq before insert or update or delete on controle_qualidade
  for each row execute function bloquear_periodo_fechado();

-- ── Auditoria ─────────────────────────────────────────────────────────────────
create table if not exists auditoria (
  id bigint generated by default as identity primary key,
  tabela text not null,
  registro_id bigint,
  acao text not null,
  antes jsonb,
  depois jsonb,
  usuario text,
  created_at timestamptz not null default now()
);

alter table auditoria enable row level security;
-- só admins logados leem o log; ninguém edita/apaga (log imutável)
create policy "auditoria_select" on auditoria for select using (auth.role() = 'authenticated');

-- security definer: o trigger grava no log mesmo quando a ação vem do funcionário (anon)
create or replace function registrar_auditoria() returns trigger
language plpgsql security definer as $$
declare
  u text;
begin
  begin
    u := coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'email', 'funcionário (PIN)');
  exception when others then
    u := 'desconhecido';
  end;
  -- o PIN nunca entra no log
  if tg_op = 'INSERT' then
    insert into auditoria (tabela, registro_id, acao, depois, usuario)
      values (tg_table_name, new.id, 'insert', to_jsonb(new) - 'pin', u);
    return new;
  elsif tg_op = 'UPDATE' then
    insert into auditoria (tabela, registro_id, acao, antes, depois, usuario)
      values (tg_table_name, new.id, 'update', to_jsonb(old) - 'pin', to_jsonb(new) - 'pin', u);
    return new;
  else
    insert into auditoria (tabela, registro_id, acao, antes, usuario)
      values (tg_table_name, old.id, 'delete', to_jsonb(old) - 'pin', u);
    return old;
  end if;
end $$;

drop trigger if exists audita_registros on registros_producao;
create trigger audita_registros after insert or update or delete on registros_producao
  for each row execute function registrar_auditoria();

drop trigger if exists audita_cq on controle_qualidade;
create trigger audita_cq after insert or update or delete on controle_qualidade
  for each row execute function registrar_auditoria();

drop trigger if exists audita_expedicoes on expedicoes;
create trigger audita_expedicoes after insert or update or delete on expedicoes
  for each row execute function registrar_auditoria();

drop trigger if exists audita_funcionarios on funcionarios;
create trigger audita_funcionarios after insert or update or delete on funcionarios
  for each row execute function registrar_auditoria();
