-- Migração — Prêmios do Programa de Parceria v3 (itens 4 e 5 do documento)
--
-- Cobre os 6 prêmios do programa:
--   · Qualificação de Parceiro (6 primeiras quinzenas, volume+qualidade progressivos)
--   · Padrinho (pago ao parceiro experiente quando o afilhado se qualifica)
--   · Anual de Produtividade (faixas de volume no ano)
--   · Fidelidade por Produção (média quinzenal de faturamento × 2)
--   · Qualidade Anual (qualidade acima do padrão em todas as quinzenas do ano)
--   · Parceiro Destaque do Ano (prêmio físico, só apuração)
--
-- A APURAÇÃO é feita no app (calcQualificacao / calcPremiosAnuais em src/lib/utils.js),
-- a partir da mesma base de tudo no programa: o APROVADO na conferência
-- (controle_qualidade.revisada). Esta tabela guarda só a CONCESSÃO — o momento em
-- que o admin reconhece o prêmio e o marca como pago —, para o prêmio não ser
-- recalculado (e mudar de valor) depois de entregue ao parceiro.

-- 1) Ingresso no programa e padrinho
-- parceria_desde: quando o parceiro entrou no PROGRAMA (≠ data de entrada na empresa).
-- É o marco zero das 6 quinzenas de qualificação; quando nulo, cai na entrada.
alter table funcionarios add column if not exists parceria_desde date;
alter table funcionarios add column if not exists padrinho_id bigint references funcionarios(id);

-- Mesmo cuidado da migração da modalidade: se o grant do anon for por coluna, as
-- colunas novas precisam entrar no grant para o app do funcionário enxergá-las.
grant select (parceria_desde, padrinho_id) on funcionarios to anon, authenticated;
grant update (parceria_desde, padrinho_id) on funcionarios to authenticated;
grant insert (parceria_desde, padrinho_id) on funcionarios to authenticated;

-- 2) Prêmios concedidos
-- referencia: o período a que o prêmio se refere — o ano ('2026') nos anuais e a
-- data-fim da 6ª quinzena ('2026-09-15') na qualificação/padrinho. Junto com
-- (func_id, tipo) forma a chave que impede conceder o mesmo prêmio duas vezes.
create table if not exists premios (
  id bigint generated by default as identity primary key,
  func_id bigint not null references funcionarios(id),
  tipo text not null check (tipo in ('qualificacao', 'padrinho', 'produtividade', 'fidelidade', 'qualidade', 'destaque')),
  referencia text not null,
  valor numeric(10,2) not null default 0,
  status text not null default 'pendente' check (status in ('pendente', 'pago')),
  data_pagamento date,
  obs text,
  registrado_por text,
  created_at timestamptz not null default now(),
  unique (func_id, tipo, referencia)
);

create index if not exists premios_func_idx on premios (func_id);

alter table premios enable row level security;

-- Mesmo modelo de acesso das demais tabelas do sistema: o funcionário (anon) precisa
-- ler para ver os próprios prêmios na tela Minha Produção; só o admin concede.
drop policy if exists "premios_select" on premios;
drop policy if exists "premios_insert" on premios;
drop policy if exists "premios_update" on premios;
drop policy if exists "premios_delete" on premios;
create policy "premios_select" on premios for select using (true);
create policy "premios_insert" on premios for insert with check (auth.role() = 'authenticated');
create policy "premios_update" on premios for update using (auth.role() = 'authenticated');
create policy "premios_delete" on premios for delete using (auth.role() = 'authenticated');

comment on table premios is 'Prêmios do Programa de Parceria concedidos (apuração é feita no app)';

-- Prêmio concedido também entra no log imutável de auditoria
drop trigger if exists audita_premios on premios;
create trigger audita_premios after insert or update or delete on premios
  for each row execute function registrar_auditoria();

-- 3) Parâmetros dos prêmios (editáveis na tela Configurações)
-- Volumes em MILHEIROS, qualidade em %, prêmios em R$.
insert into configuracoes (chave, valor) values
  -- Qualificação: 6 quinzenas em 3 etapas de exigência crescente (60% / 80% / 100% do alvo)
  ('qualif_vol1',        '7'),
  ('qualif_qual1',       '94'),
  ('qualif_vol2',        '10'),
  ('qualif_qual2',       '96'),
  ('qualif_vol3',        '12'),
  ('qualif_qual3',       '97'),
  ('premio_qualificacao', '300'),
  ('premio_padrinho',    '150'),
  -- Anual de produtividade: 3 faixas de volume no ano
  ('premio_prod_v1',     '250'),
  ('premio_prod_p1',     '500'),
  ('premio_prod_v2',     '400'),
  ('premio_prod_p2',     '1000'),
  ('premio_prod_v3',     '550'),
  ('premio_prod_p3',     '1500'),
  -- Fidelidade: volume mínimo no ano; valor = faturamento do ano ÷ 24 × 2
  ('premio_fid_min',     '250'),
  -- Qualidade anual: prêmio fixo + volume mínimo para concorrer
  ('premio_qual_anual',  '500'),
  ('premio_qual_min',    '200')
on conflict (chave) do nothing;
