-- Estoque & Expedição
-- Entrada de estoque = displays registrados no empacotamento (controle_qualidade.display).
-- Saída = expedições de displays para o distribuidor, registradas nesta tabela.

create table if not exists expedicoes (
  id bigint generated by default as identity primary key,
  data date not null default current_date,
  tipo text not null default 'Original' check (tipo in ('Original', 'Menta', 'Ouro', 'Outro')),
  displays integer not null check (displays > 0),
  obs text,
  registrado_por text,
  created_at timestamptz not null default now()
);

alter table expedicoes enable row level security;

-- Mesmo modelo de acesso das demais tabelas do sistema
create policy "expedicoes_select" on expedicoes for select using (true);
create policy "expedicoes_insert" on expedicoes for insert with check (true);
create policy "expedicoes_update" on expedicoes for update using (true);
create policy "expedicoes_delete" on expedicoes for delete using (true);

comment on table expedicoes is 'Saídas de displays do estoque (vendas ao distribuidor)';
